config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes
  
  authenticated :user do 
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = Note.where(user_id: current_user)
  end

  def show

  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end 

  def edit

  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :message)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title VladderNote | Evernote Rails Clone
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %link{:rel => "stylesheet", :href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
  = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to image_tag( 'logo.png'), root_path, id: "logo"
      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :message
  = f.button :submit, class: "button"
  

app/views/notes/edit.html.haml
.wrapper_with_padding
  %h1 Edit your note

  = render 'form'

  = link_to "Cancel", note_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    - unless @notes.blank?
      - @notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    -else
      %h2 Add a Note
      %p It looks like you've yet to create a note. You should add a note below.
      %button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 Add a new Note

  =render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show

    %h1.title= @note.title
    %p= simple_format(@note.message)

    -# = link_to "All Notes", notes_path
    .buttons
      = link_to "Edit", edit_note_path(@note), class: "button"
      = link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Do you really want to delete?" }, class: "button"

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 VladderNote
    %p The Rails Evernote Clone. Keep your thoughts together.
    %button= link_to "Sign Up", new_user_registration_path

#testimonial
  .wrapper
    %p.quote "The best Evernote clone I've ever used, granted I've only used one but trust me, this is amazing!"
    %p.name - Vlad Marinov

#callouts
  .callout_inner 
    .wrapper 
      .callout
        %i.fa.fa-paper-plane
        %h2 Easy To Use
        %p Our application is extremely easy to use, just like making a paper plane. The simplicity of the interface makes it easy to navigate, style, and share (coming soon) your notes with others as a way of keeping your thoughts private. Support is available in case needed but the interface is so simple that you might not even need it. 
    .wrapper 
      .callout
        %i.fa.fa-paperclip
        %h2 Take Notes
        %p You can take notes with the press of a few buttons and get right onto dictating whatever you need. The notes are always available online and can be opened anywhere as long as you sign into your account. There are no fees and no advertisements. Our end goal is user satisfaction and happiness.
    .wrapper
      .callout
        %i.fa.fa-code
        %h2 Edit Using HTML
        %p Notes can be easily styled and organized using HTML tags. This allows for a universal notation method that can easily be used by many people. Essentially the goal is to make notes fun to edit and a way to organize your thoughts in a way that benefit you.   

#bottom_cta
  .wrapper
    %h2 Fo Shizzle!
    %p You guys should sign up, this stuff is really cool
    %button= link_to "You Should Press Me", new_user_registration_path

%footer
  %p &copy Vlad Marinov 2015